version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - DATABASE_URL=postgresql://user:password@db:5432/fridgy?schema=public
    depends_on:
      db:
        condition: service_healthy # Čeka dok db ne bude zdrav
    command: >
      sh -c "npm run migrate && npm start"

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fridgy
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fridgy"] # Provjerava je li baza spremna
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
